---
title: "Ecoli Ampicilin"
author: "Kejia Li"
date: "2025-03-07"
output:
  html_document:
    keep_md: true
    toc: true
    theme: united
    toc_float: true
    code_folding: hide
  pdf_document:
    toc: true
editor_options:
  
  chunk_output_type: console
---


# 1.General settings 

## 1.1 Chunk settings

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  include = TRUE,
  cache = TRUE,
  cache.lazy = FALSE,
  eval = TRUE,
  fig.width = 4 * (1 + sqrt(5)) / 2, 
  fig.height = 4,
  dpi = 700
)
```


## 1.2 Packages

```{r, message=F, warning =F}
library(tidyverse)
library(ggplot2)
library(reshape2)
library(ggrepel)
library(knitr)
library(ggpubr)
library(ggforce)
library(UniprotR)
library(Peptides)
library(biomaRt)
library(Biostrings)
library(limma)
library(vroom)
library(stringr)
library(corrplot)
library(ggh4x)
library(openxlsx)
library(htmltools)
library(ComplexUpset)


mutate <- dplyr::mutate
select <- dplyr::select
group_by <- dplyr::group_by
filter <- dplyr::filter
rename <- dplyr::rename

```


## 1.3 Graphics

```{r}

mytheme <- theme_bw()+theme( 
  panel.background = element_rect(color = "black",size=0.5),
  axis.title = element_text(colour="black",size=9),
  axis.text  = element_text(size=8,color="black"),
  legend.position = "right",legend.key.size = unit(0.5,"cm"),
  legend.title = element_blank(),
  legend.text =element_text(colour = "black",size=8)
)

```


# 2. Import data

```{r}

amipicillin <- vroom::vroom("Crude_Ecoli_lysates_ampicilin_report.pr_matrix.tsv")
colnames(amipicillin)


diann_prec_add_peptide_pos2 <- function(data_precursor, fasta, silent = T) {
  
  if (!hasArg(data_precursor)) stop("Please specify a data frame or a tibble of the DIA-NN precursors.")
  
  if (!hasArg(fasta)) fasta <- choose.files(multi = F, )
  fasta <- Biostrings::readAAStringSet(fasta)
  fasta <- as.character(fasta)
  names(fasta) <- unlist(lapply(strsplit(x = names(fasta), "\\|"), \(x) x[2]))
  
  if (!silent) {
    message(paste0(nrow(data_precursor), " precursors identified. This should take around ", 
                   round(nrow(data_precursor) * 0.0000884 + 0.1463016, 2), " s."))
    t0 <- Sys.time()
  }
  
  # Add peptide positions
  data_pos <- data_precursor %>% 
    dplyr::rowwise() %>% 
    dplyr::mutate(peptide.length = nchar(Stripped.Sequence), 
                  from = regexpr(Stripped.Sequence, as.character(fasta[unlist(strsplit(Protein.Group, ";"))[1]]))[1], 
                  to = from + peptide.length - 1, 
                  .after = Modified.Sequence) %>% 
    dplyr::ungroup()
  
  if (!silent) {
    t1 <- Sys.time()
    
    duration <- t1 - t0
    
    if (duration > nrow(data_precursor) * 0.0000884 + 0.1463016) {
      message(paste0("Sorry for the delay! It took ", round(duration, 2), " s."))
    } else {
      message(paste0("Wow, even faster! It only took ", round(duration, 2), " s."))
    }
  }
  
  return(data_pos)
  
}


# Input the imported precursor data frame and specify the fasta file
fasta_path <- "uniprotkb_ecoli_AND_model_organism_8333_2024_06_06.fasta"

Annotated_amipicillin <- diann_prec_add_peptide_pos2(amipicillin, fasta_path, F)

```


# 3. Divide into two groups

```{r}

renamed_ampicillin <- Annotated_amipicillin %>%
  select(1:21) %>%
  rename(
    control_1 = 14, control_2 = 15, control_3 = 16,
    control_4 = 17, drug_1 = 18, drug_2 = 19,
    drug_3 = 20, drug_4 = 21)

```


# 4. Statistic test analysis

```{r, include=FALSE,eval=FALSE}

analyze_data <- function(data, dataset_name) {
  
  
  # step-1：data-processing
  peptide_intensity <- data %>%
    group_by(Stripped.Sequence) %>%
    mutate(across(c(drug_1, drug_2, drug_3, drug_4, control_1, control_2, control_3, control_4), ~sum(.x, na.rm = TRUE), .names = "sum_{col}")) %>%
    select(Protein.Ids, Genes, First.Protein.Description, Stripped.Sequence, peptide.length, from, to, 
           starts_with("sum_")) %>%
    distinct(Stripped.Sequence, .keep_all = TRUE) %>%
    ungroup() %>%
    filter(rowSums(.[8:15] == 0) == 0)
  
  
  # step-2：Bayes t-test
  data <- peptide_intensity %>% select(c(1:7, 12:15, 8:11))
  columnnames <- c("Protein.Ids", "Genes", "name", "sequence", "length", "start", "end", 
                   "control_1", "control_2", "control_3", "control_4", "D1_1", "D1_2", "D1_3", "D1_4", "UID")
  design <- model.matrix(~ 0 + factor(c(0, 0, 0, 0, 1, 1, 1, 1))) # 0=Vehicle; 1=Drug
  colnames(design) <- c("V", "D") # 0=Vehicle; 1=Drug
  
  data.DIA <- grep("_", colnames(data))
  data[, data.DIA] <- log((data[, data.DIA]), base = 2)
  data.metanms <- grep("Stripped.Sequence", colnames(data))
  data$last <- (regexpr(';', as.character(data$Protein.Ids)) - 1) # if no ";" then = -1
  data$UID <- ifelse(data$last > 0, (substr(as.character(data$Protein.Ids), 1, data$last)),
                     (as.character(data$Protein.Ids)))
  data$last <- NULL
  intensity <- grep("_", colnames(data))
  data <- setNames(data, columnnames)
  data$ID <- 1:nrow(data)
  
  fit <- lmFit(data[, intensity], design)
  fit <- eBayes(fit) ## Apply empirical Bayes smoothing to the standard errors.
  contrast <- makeContrasts("D-V", levels = design)
  fit2 <- contrasts.fit(fit, contrast)
  fit2 <- eBayes(fit2, trend = TRUE)
  
  ptopf <- topTableF(fit2, adjust = "BH", genelist = data[, c("ID")], number = Inf)
  ptopf$rank <- 1:length(ptopf$F)
  ptopf$numfp <- ptopf$rank * ptopf$adj.P.Val
  
  t.stat <- topTable(fit2, adjust = "BH", genelist = data[, "ID"], coef = 1, p.value = 1, number = Inf)
  nms <- grep("logFC", colnames(t.stat)) 
  colnames(t.stat)[nms] <- "Log2FC"
  t.stat$Log10P.Value <- -log(t.stat$P.Value, base = 10)
  t.stat$Log10adj.P.Val <- -log(t.stat$adj.P.Val, base = 10)
  t.statNMS <- t.stat[c("ID", "Log2FC", "Log10P.Value", "Log10adj.P.Val", "P.Value", "adj.P.Val", "AveExpr", "t", "B")]
  t.stat <- t.statNMS
  
  data.analysis <- merge(t.stat, data, by = "ID", all = TRUE, sort = FALSE)
  
  
  
  # write csv
  write.csv(data.analysis, file = paste0("bayes_test_",dataset_name,".csv"))
  
  
}



datasets <- list(
  ecoli_ampicillin = renamed_ampicillin)


walk2(datasets, names(datasets), ~ analyze_data(.x, .y))


```


# 5. Fig.3D: Volcano plot showing the Ampicillin target identification in Ecoli crude lysates


```{r,echo=TRUE}

data <- read.csv("bayes_test_ecoli_ampicillin.csv")

protein <- data %>%
  distinct(Genes, .keep_all = TRUE) %>%
  mutate(is.known = ifelse(Genes %in% c("dacB","ftsI","mrcA","mrcB","pbpG"),"yes","no"))


p <- ggplot(data = protein, aes(x = Log2FC, y = Log10P.Value, fill = is.known)) +
  geom_point(shape = 21,color = "black", size = 2, alpha = 0.7,stroke= 0.2) +  
  scale_fill_manual(name= "is.known",breaks = c("yes","no"), values = c("#E69F00","#b3b3b3"))+
  geom_text_repel(
    data = subset(protein, Log10P.Value >3.4),
    aes(label = Genes),
    size = 4,  
    box.padding = unit(0.1, "lines"),  
    point.padding = unit(0.3, "lines"),  
    segment.color = "grey50",  
    show.legend = FALSE,
    max.overlaps = 20
  ) + scale_x_continuous(
    name = expression(Log["2"] * FC),
    limits = c(-4, 4),
    breaks = -4:4
  ) +
  scale_y_continuous(
    name = expression(-Log["10"] * Pvalue),
    limits = c(0, 10),
    breaks = seq(0, 10, by = 2)
  ) +
  labs(
    title = "Ecoli_ampicilin",
    color = "is.Known"  
  ) +
  annotate(
    "text", 
    x = 0, y = 10, 
    label = paste0("Protein number = ", nrow(protein)), 
    size = 5, 
    hjust = 0.5, 
    vjust = 1.5, 
    color = "black"
  ) +
  theme_minimal()+ 
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5), 
    axis.title = element_text(size = 12), 
    axis.text = element_text(size = 12,color="black"), 
    legend.title = element_text(size = 12), 
    legend.text = element_text(size = 10),  
    panel.grid.major = element_line(color = "grey80", linewidth = 0.2),  
    panel.grid.minor = element_blank(),  
    panel.background = element_rect(fill = "white", color = "black", linewidth = 1),  
    plot.background = element_rect(fill = "white",colour = NA),axis.ticks = element_line(color = "black", linewidth = 0.5),  
    axis.ticks.length = unit(0.2, "cm")  
  )

p


ggsave(paste0("Fig.3D",".pdf"),width = 6,height = 5.5,useDingbats=FALSE)

```


# 6. Fig.3E: Compare with in-vivo and lysates TPP


```{r,echo=TRUE}


pelsa <- read.csv("bayes_test_ecoli_ampicillin.csv") %>%
  distinct(Genes, .keep_all = TRUE) %>%
  mutate(is.known = ifelse(Genes %in% c("dacB","ftsI","mrcA","mrcB","pbpG"),"yes","no"))%>% 
  head(10) %>% 
  select(UID,is.known) %>% 
  rename(Uniprot_id = 1) %>% 
  mutate(type="HT-PELSA(lysates)")


## TPP datasets are extracted from the literature: https://doi.org/10.15252/msb.20188242

TPP_UID <- openxlsx::read.xlsx("TPP_ecoli_ampicillin_invivo.xlsx", sheet= 3) %>% 
  select(1:2) %>% 
  unique() 

TPP_invivo_targets <- openxlsx::read.xlsx("TPP_ecoli_ampicillin_invivo.xlsx", sheet= 4) %>%  left_join(TPP_UID, by = "gene_name") %>% 
  mutate(is.known = ifelse(gene_name %in% c("MRCA","FTSI","DACB","PBPG"),"yes","no")) %>% 
  select(Uniprot_id, is.known) %>% 
  mutate(type ="TPP(in vivo)")

TPP_lysates_targets <- openxlsx::read.xlsx("TPP_ecoli_ampicillin_lysates.xlsx", sheet= 4) %>%  left_join(TPP_UID, by = "gene_name") %>% 
  mutate(is.known = ifelse(gene_name %in% c("MRCA","DACB"),"yes","no")) %>%
  select(Uniprot_id, is.known) %>% 
  mutate(type = "TPP(lysates)")

all <- rbind(pelsa,TPP_invivo_targets,TPP_lysates_targets)

write.csv(all,"SourceData_Fig.3E.CSV")



gene_set_matrix <- all %>%
  mutate(Present = TRUE) %>%
  pivot_wider(names_from = type, values_from = Present, values_fill = FALSE)

gene_categories <- all %>%
  distinct(Uniprot_id, is.known)

upset_data <- left_join(gene_set_matrix, gene_categories, by = "Uniprot_id")
colnames(upset_data)


pdf("Fig.3E.pdf", width = 8, height = 6)

upset(
  upset_data,
  intersect = c("TPP(in vivo)","TPP(lysates)","HT-PELSA(lysates)" ),sort_sets=FALSE,
  name = "Gene Sets",
  base_annotations = list(
    'Intersection size' = intersection_size(aes(fill = is.known.x)) +
      scale_fill_brewer(palette = "Set2")),
  sort_intersections = FALSE,
  intersections=list(
    "TPP(in vivo)","TPP(lysates)",
    c("TPP(in vivo)","TPP(lysates)"),
    "HT-PELSA(lysates)",
    c("HT-PELSA(lysates)", "TPP(in vivo)"),
    c("HT-PELSA(lysates)", "TPP(in vivo)","TPP(lysates)")),
  set_sizes = (
    upset_set_size(geom=geom_bar(
      aes(fill=is.known.x),
      width=0.5))+ scale_fill_brewer(name = "",palette = "Set2")+
      theme(legend.position = "none")))


dev.off()

```


# 7 Fig.S5G: Local stability of mrcA 

```{r, echo=TRUE}

## Refer to section 4 to obtain "bayes_test_ecoli_ampicillin.csv";

all_peptides <- vroom::vroom ("bayes_test_ecoli_ampicillin.csv")

protein <- "mrcA"

POI <- all_peptides %>% 
  filter(Genes == protein) %>% 
  mutate(abs= abs(Log2FC)) %>% 
  mutate(in.domain = case_when(
    end > 48 & start < 216  ~ "Transglycosylase",
    start > 400 & start < 710 ~ "Transpeptidase",
    TRUE ~ "no" ))

POI_filter <- POI %>% filter(!(abs> 0.3 & Log10P.Value <2))

write.csv(POI_filter, "mrcA_peptides.csv")

shadow_rect <- data.frame(
  xmin = 0, 
  xmax = 850, 
  ymin = -0.3, 
  ymax = 0.3
)

shadow_rect_1 <- data.frame(
  xmin = 48,
  xmax = 216,
  ymin= -2,
  ymax= -1.8)


shadow_rect_2 <- data.frame(
  xmin = 400,
  xmax = 710,
  ymin= -2,
  ymax= -1.8)


p <- ggplot() +
  geom_segment(data = POI_filter, aes(x = start, xend = end,
                                      y = Log2FC, color = in.domain),linewidth = 1.5) +  
  scale_color_manual(values = c("Transglycosylase"= "#6bacb3",
                                "Transpeptidase"="#d35e54",
                                "no" ="black"))+
  geom_rect(data = shadow_rect, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "grey", alpha = 0.3)+
  geom_rect(data = shadow_rect_1, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "#6bacb3", alpha = 0.9)+
  geom_rect(data = shadow_rect_2, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "#d35e54", alpha = 0.9)+
  
  scale_x_continuous(name="sequence",limits = c(0,850),breaks = c(0,100,200,300,400,500,600,700),expand = c(0, 0))+
  scale_y_continuous(name=expression(Log["2"]*FC),limits =c(-2,1),breaks = c(-1,0,1,2,3),expand = c(0, 0))+
  theme( 
    panel.background = element_rect(color = "black",size=0.5),
    axis.title.x = element_text(colour="black",size=15),
    axis.title.y = element_text(colour="black",size=15),
    axis.text  = element_text(size=20,color="black"),
    axis.ticks = element_line(linewidth  = 2),
    legend.position = "none",legend.key.size = unit(0.35,"cm"),
    legend.title = element_blank(),
    legend.text =element_text(colour = "black",size=15)
  )+theme_bw()+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank())+
  ggtitle(paste0(protein, ", Ampicillin"))+
  theme(axis.text = element_text(color = "black", size=8),
        axis.title = element_text(size=9),title = element_text(size=8))+
  force_panelsizes(rows = unit(2, "in"), cols = unit(2.5, "in"))

p

ggsave("Fig.S5G.pdf",width=3,height=2.8,dpi = 300)

```


# 8 Fig.S5H: Local stability of mrcB

```{r, echo=TRUE}

## for mrcB 

protein <- "mrcB"

POI <- all_peptides %>% 
  filter(Genes == protein) %>% 
  mutate(abs= abs(Log2FC)) %>% 
  mutate(in.domain = case_when(
    end > 195 & start < 367  ~ "Transglycosylase",
    start > 444 & start < 736 ~ "Transpeptidase",
    TRUE ~ "no"
  ))

POI_filter <- POI %>% filter(!(abs> 0.3 & Log10P.Value <2))


write.csv(POI_filter, "mrcB_peptides.csv")

shadow_rect <- data.frame(
  xmin = 0, 
  xmax = 844, 
  ymin = -0.3, 
  ymax = 0.3
)

shadow_rect_1 <- data.frame(
  xmin = 48,
  xmax = 216,
  ymin= -1,
  ymax= -0.8)


shadow_rect_2 <- data.frame(
  xmin = 400,
  xmax = 710,
  ymin= -1,
  ymax= -0.8)


p <- ggplot() +
  geom_segment(data = POI_filter, aes(x = start, xend = end,
                                      y = Log2FC, color = in.domain),linewidth = 1.5) +  
  scale_color_manual(values = c("Transglycosylase"= "#6bacb3",
                                "Transpeptidase"="#d35e54",
                                "no" ="black"))+
  geom_rect(data = shadow_rect, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "grey", alpha = 0.3)+
  geom_rect(data = shadow_rect_1, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "#6bacb3", alpha = 0.9)+
  geom_rect(data = shadow_rect_2, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "#d35e54", alpha = 0.9)+
  
  scale_x_continuous(name="sequence",limits = c(0,850),breaks = c(0,100,200,300,400,500,600,700),expand = c(0, 0))+
  scale_y_continuous(name=expression(Log["2"]*FC),limits =c(-1,3),breaks = c(-1,0,1,2,3),expand = c(0, 0))+
  theme( 
    panel.background = element_rect(color = "black",size=0.5),
    axis.title.x = element_text(colour="black",size=15),
    axis.title.y = element_text(colour="black",size=15),
    axis.text  = element_text(size=20,color="black"),
    axis.ticks = element_line(linewidth  = 2),
    legend.position = "none",legend.key.size = unit(0.35,"cm"),
    legend.title = element_blank(),
    legend.text =element_text(colour = "black",size=15)
  )+theme_bw()+theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank())+
  ggtitle(paste0(protein, ", Ampicillin"))+
  theme(axis.text = element_text(color = "black", size=8),
        axis.title = element_text(size=9),title = element_text(size=8))+
  force_panelsizes(rows = unit(2, "in"), cols = unit(2.5, "in"))

p

ggsave("Fig.S5H.pdf", width = 3, height = 2.8, dpi = 300)

```

